### ISSUE TITLE
404 Not Found when use nginx-stable

### ISSUE THREAD

**Issue by patsevanton** [yandex-cloud/docs#166]
**helm repo add nginx-stable https://helm.nginx.com/stable**
```
"nginx-stable" has been added to your repositories
```

**helm repo update**
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nginx-stable" chart repository
...Successfully got an update from the "grafana" chart repository
Update Complete. ⎈Happy Helming!⎈
```

**helm install nginx-ingress nginx-stable/nginx-ingress**
```
NAME: nginx-ingress
LAST DEPLOYED: Sun Jul 18 22:06:52 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NGINX Ingress Controller has been installed.
```

**kubectl get all -A**
```
NAMESPACE     NAME                                               READY   STATUS    RESTARTS   AGE
default       pod/nginx-ingress-nginx-ingress-6695d454cb-z5lf7   1/1     Running   0          21s
kube-system   pod/coredns-7c646474c9-9t8hw                       1/1     Running   0          22m
kube-system   pod/ip-masq-agent-49hxj                            1/1     Running   0          12m
kube-system   pod/kube-dns-autoscaler-7c867cbf8d-2q648           1/1     Running   0          22m
kube-system   pod/kube-proxy-rfpsl                               1/1     Running   0          12m
kube-system   pod/metrics-server-v0.3.1-b5dcfd6c5-5rwk8          2/2     Running   0          12m
kube-system   pod/npd-v0.8.0-8mdvh                               1/1     Running   0          12m
kube-system   pod/yc-disk-csi-node-v2-8d99d                      6/6     Running   0          12m

NAMESPACE     NAME                                  TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       service/kubernetes                    ClusterIP      10.96.128.1     <none>           443/TCP                      22m
default       service/nginx-ingress-nginx-ingress   LoadBalancer   10.96.173.134   130.193.35.185   80:31318/TCP,443:30541/TCP   22s
kube-system   service/kube-dns                      ClusterIP      10.96.128.2     <none>           53/UDP,53/TCP                22m
kube-system   service/metrics-server                ClusterIP      10.96.182.167   <none>           443/TCP                      22m

NAMESPACE     NAME                                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                                        AGE
kube-system   daemonset.apps/ip-masq-agent                    1         1         1       1            1           beta.kubernetes.io/os=linux,node.kubernetes.io/masq-agent-ds-ready=true              22m
kube-system   daemonset.apps/kube-proxy                       1         1         1       1            1           kubernetes.io/os=linux,node.kubernetes.io/kube-proxy-ds-ready=true                   22m
kube-system   daemonset.apps/npd-v0.8.0                       1         1         1       1            1           beta.kubernetes.io/os=linux,node.kubernetes.io/node-problem-detector-ds-ready=true   22m
kube-system   daemonset.apps/nvidia-device-plugin-daemonset   0         0         0       0            0           beta.kubernetes.io/os=linux,node.kubernetes.io/nvidia-device-plugin-ds-ready=true    22m
kube-system   daemonset.apps/yc-disk-csi-node                 0         0         0       0            0           <none>                                                                               22m
kube-system   daemonset.apps/yc-disk-csi-node-v2              1         1         1       1            1           yandex.cloud/pci-topology=k8s                                                        22m

NAMESPACE     NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
default       deployment.apps/nginx-ingress-nginx-ingress   1/1     1            1           23s
kube-system   deployment.apps/coredns                       1/1     1            1           22m
kube-system   deployment.apps/kube-dns-autoscaler           1/1     1            1           22m
kube-system   deployment.apps/metrics-server-v0.3.1         1/1     1            1           22m

NAMESPACE     NAME                                                     DESIRED   CURRENT   READY   AGE
default       replicaset.apps/nginx-ingress-nginx-ingress-6695d454cb   1         1         1       23s
kube-system   replicaset.apps/coredns-7c646474c9                       1         1         1       22m
kube-system   replicaset.apps/kube-dns-autoscaler-7c867cbf8d           1         1         1       22m
kube-system   replicaset.apps/metrics-server-v0.3.1-7b6667ff99         0         0         0       22m
kube-system   replicaset.apps/metrics-server-v0.3.1-b5dcfd6c5          1         1         1       12m
```

**Install grafana to IP 130.193.35.185**
```
helm install --atomic \
--set ingress.enabled=true \
--set ingress.hosts[0]=grafana.130-193-35-185.my.local-ip.co \
grafana grafana/grafana
```

**kubectl get ingress -A**
```
NAMESPACE   NAME      CLASS    HOSTS                                   ADDRESS   PORTS   AGE
default     grafana   <none>   grafana.130-193-35-185.my.local-ip.co             80      7m43s
```

![image](https://user-images.githubusercontent.com/10828883/126074560-3049e411-e7b9-4fd9-b8cc-74cb232b0952.png)

**Comment by patsevanton** [comment]
**helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx**
```
"ingress-nginx" already exists with the same configuration, skipping
```

**helm repo update**
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "grafana" chart repository
Update Complete. ⎈Happy Helming!⎈
```

**helm install ingress-nginx ingress-nginx/ingress-nginx**
```
NAME: ingress-nginx
LAST DEPLOYED: Sun Jul 18 22:35:37 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The ingress-nginx controller has been installed.
It may take a few minutes for the LoadBalancer IP to be available.
You can watch the status by running 'kubectl --namespace default get services -o wide -w ingress-nginx-controller'

An example Ingress that makes use of the controller:

  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
    name: example
    namespace: foo
  spec:
    rules:
      - host: www.example.com
        http:
          paths:
            - backend:
                serviceName: exampleService
                servicePort: 80
              path: /
    # This section is only required if TLS is to be enabled for the Ingress
    tls:
        - hosts:
            - www.example.com
          secretName: example-tls

If TLS is enabled for the Ingress, a Secret containing the certificate and key must also be provided:

  apiVersion: v1
  kind: Secret
  metadata:
    name: example-tls
    namespace: foo
  data:
    tls.crt: <base64 encoded cert>
    tls.key: <base64 encoded key>
  type: kubernetes.io/tls
```

**kubectl get all -A**
```
NAMESPACE     NAME                                           READY   STATUS    RESTARTS   AGE
default       pod/ingress-nginx-controller-c7d64c64d-fd2dz   0/1     Running   0          17s
kube-system   pod/coredns-7c646474c9-phqlc                   1/1     Running   0          9m8s
kube-system   pod/ip-masq-agent-nkpqg                        1/1     Running   0          3m41s
kube-system   pod/kube-dns-autoscaler-7c867cbf8d-vjz8j       1/1     Running   0          9m6s
kube-system   pod/kube-proxy-lc8n9                           1/1     Running   0          3m41s
kube-system   pod/metrics-server-v0.3.1-b5dcfd6c5-4lj2m      2/2     Running   0          3m25s
kube-system   pod/npd-v0.8.0-ts7d6                           1/1     Running   0          3m41s
kube-system   pod/yc-disk-csi-node-v2-l9g97                  6/6     Running   0          3m41s

NAMESPACE     NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
default       service/ingress-nginx-controller             LoadBalancer   10.96.151.71    84.252.132.112   80:30039/TCP,443:31622/TCP   17s
default       service/ingress-nginx-controller-admission   ClusterIP      10.96.211.248   <none>           443/TCP                      17s
default       service/kubernetes                           ClusterIP      10.96.128.1     <none>           443/TCP                      9m28s
kube-system   service/kube-dns                             ClusterIP      10.96.128.2     <none>           53/UDP,53/TCP                9m10s
kube-system   service/metrics-server                       ClusterIP      10.96.139.139   <none>           443/TCP                      9m9s

NAMESPACE     NAME                                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                                        AGE
kube-system   daemonset.apps/ip-masq-agent                    1         1         1       1            1           beta.kubernetes.io/os=linux,node.kubernetes.io/masq-agent-ds-ready=true              9m7s
kube-system   daemonset.apps/kube-proxy                       1         1         1       1            1           kubernetes.io/os=linux,node.kubernetes.io/kube-proxy-ds-ready=true                   9m7s
kube-system   daemonset.apps/npd-v0.8.0                       1         1         1       1            1           beta.kubernetes.io/os=linux,node.kubernetes.io/node-problem-detector-ds-ready=true   9m10s
kube-system   daemonset.apps/nvidia-device-plugin-daemonset   0         0         0       0            0           beta.kubernetes.io/os=linux,node.kubernetes.io/nvidia-device-plugin-ds-ready=true    9m7s
kube-system   daemonset.apps/yc-disk-csi-node                 0         0         0       0            0           <none>                                                                               9m9s
kube-system   daemonset.apps/yc-disk-csi-node-v2              1         1         1       1            1           yandex.cloud/pci-topology=k8s                                                        9m9s

NAMESPACE     NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
default       deployment.apps/ingress-nginx-controller   0/1     1            0           18s
kube-system   deployment.apps/coredns                    1/1     1            1           9m9s
kube-system   deployment.apps/kube-dns-autoscaler        1/1     1            1           9m10s
kube-system   deployment.apps/metrics-server-v0.3.1      1/1     1            1           9m10s

NAMESPACE     NAME                                                 DESIRED   CURRENT   READY   AGE
default       replicaset.apps/ingress-nginx-controller-c7d64c64d   1         1         0       18s
kube-system   replicaset.apps/coredns-7c646474c9                   1         1         1       9m9s
kube-system   replicaset.apps/kube-dns-autoscaler-7c867cbf8d       1         1         1       9m10s
kube-system   replicaset.apps/metrics-server-v0.3.1-7b6667ff99     0         0         0       9m10s
kube-system   replicaset.apps/metrics-server-v0.3.1-b5dcfd6c5      1         1         1       3m26s
```

Install grafana to IP 84.252.132.112
```
helm install --atomic \
--set ingress.enabled=true \
--set ingress.hosts[0]=grafana.84-252-132-112.my.local-ip.co \
grafana grafana/grafana
```


**kubectl get ingress -A**
```
NAMESPACE   NAME      CLASS    HOSTS                                   ADDRESS          PORTS   AGE
default     grafana   <none>   grafana.84-252-132-112.my.local-ip.co   84.252.132.112   80      40s
```

![image](https://user-images.githubusercontent.com/10828883/126075307-c94e1eb0-48db-4d51-85de-8a50c5a8b856.png)
