### ISSUE TITLE
Kubernetes. Сломана интеграция с Object Storage

### ISSUE THREAD

**Issue by pelid** [yandex-cloud/docs#301]
Пытался настроить `geesefs` так, чтобы подключить распознавание mime-types. В справке к `geesefs` нашёл подходящую опцию `--use-content-type` и указал её в yaml-манифесте `StorageClass`, как это предложено в туториале ["Интеграция с Object Storage"](https://cloud.yandex.ru/docs/managed-kubernetes/operations/volumes/s3-csi-integration), но не сработало.

Делал так:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  options: "--use-content-type --memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  …
```

Исследовал проблему и выяснил, что `geesefs` корректно реагирует на опцию `--use-content-type`, если запускать его напрямую на своей машине. Но в Kubernetes настройка `parameters.options` теряется.

Смог обойти проблему, добавив настройку `options` ещё и в `PersistentVolume` вместо `StorageClass`:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bucket
spec:
  storageClassName: csi-s3
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: bucket
    volumeAttributes:
      capacity: 6Gi
      mounter: geesefs
      options: '--use-content-type --memory-limit 1000 --dir-mode 0777 --file-mode 0666'
    …
```

Сейчас туториал вводит в заблуждение. Пришлось потратить несколько часов, чтобы найти решение проблемы. Хорошо бы упомянуть о проблеме в документации.

PS. Не важно как настраивать интеграцию -- по туториалу или из Marketplace. В обоих случаях теряется настройка `parameters.options` в `StorageClass`.
