### ISSUE TITLE
Ошибка в yaml "Работа с группой виртуальных машин с автоматическим масштабированием"

### ISSUE THREAD

**Issue by sfedu-admin** [yandex-cloud/docs#471]
Здравствуйте!

Сценарий "Работа с группой виртуальных машин с автоматическим масштабированием" по доке https://cloud.yandex.ru/docs/compute/tutorials/vm-autoscale из UI

specification.yaml
```
disk_spec:
      type_id: network-hdd
      size: 10G
      image_id: fd8iv792kirahcnqnt0q # Идентификатор публичного образа Container Optimized Image.
```
Приведенный в сценарии yaml скрипт не будет работать. С текущей версией container-optimized-image требуется диск 30+ Гб. Об этом говорится в ошибке:

```
$ yc compute instance-group create --file=nlb-spec.yaml 
ERROR: rpc error: code = InvalidArgument desc = Request validation error: Disk size must be greater or equal than 30.0 GB
```
 Следует увеличить размер диска до 30G.
