### ISSUE TITLE
Добавьте плиз доку как сделать Ingress для 2+ доменов в Managed Service for Kubernetes

### ISSUE THREAD

**Issue by arturgspb** [yandex-cloud/docs#50]
Сейчас понятно как сделать это через Service type=LoadBalancer, но мне надо в одном Kubernates расположить несколько приложений на разных доменах или подурлах. Вчера целый день боролся и так и не понял как это сделать, а это останавливает от миграции к вам =(

Хочу такую схему:
LoadBalancer -> K8s Ingress -> K8s Service -> K8s Pod
Может это неправильно и мне не надо этого хотеть, тогда поправьте плиз.

Я не конкретно про этот вариант, а про примерно мой случай - куча микросервисах и каждый на своем домене или подурлах одного домена:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: service1
          servicePort: 4200
      - path: /bar
        backend:
          serviceName: service2
          servicePort: 8080
```

P.S. Пожалуйста помогите это сделать, очень надо. Если будет нужно - свяжитесь лично. 
Канал в телеграме у меня выдает ошибку - я туда добавился, написал первое сообщение и меня будто забанило и я не могу ни читать, ни писать там.
