### ISSUE TITLE
Асинхронный вызов функции с помощью API Gateway extension

### ISSUE THREAD

**Issue by nezort11** [yandex-cloud/docs#905]
В документации по асинхронному вызову функции написано, что для асинхронного вызова необходимо добавить параметр `?integration=async` в URL вызова фукнции

https://github.com/yandex-cloud/docs/blob/a88d0cefa14748ec93ea0e3a4d315d7944bfc9e8/en/functions/concepts/function-invoke-async.md?plain=1#L12

пример такого вызова:

```sh
curl "https://functions.yandexcloud.net/$FUNCTION_ID?integration=async" \
```
https://github.com/nikolaymatrosov/sls-rosetta/blob/2753a7204686a5195342f952939b376f8141f68f/examples/typescript/async/README.md?plain=1#L40

Вопрос в том как добиться асинхронного вызова функции когда функция вызывается с помощью API Gateway extension https://yandex.cloud/en/docs/api-gateway/concepts/extensions/cloud-functions:

```yaml
/example/{ID}:
    get:
      summary: Get ID
      parameters:
        - name: integration
          in: query
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: b095c95icnvb********
        tag: "$latest"
        service_account_id: ajehfe56hhl********
```

В данном случае когда я пытаюсь сделать:

```sh
curl https://<gateway domain>.apigw.yandexcloud.net/webhook?integration=async
```

Функция все равно **вызывается синхронно** 

В дашборде API Gateway пишется сколько времени заняло вызов функции (хотя по идеи она всегда должна _мгновенно_ возвращать 200)
<img width="449" alt="Image" src="https://github.com/user-attachments/assets/532f78e0-c89d-4012-a51a-d4b89b4cb58e" />
