### ISSUE TITLE
Установка Fluent Bit для сбора логов подов и сервисов: недостаточно инфомрации

### ISSUE THREAD

**Issue by natkorch** [yandex-cloud/docs#920]
Инструкция для установки Fluent Bit в Manages service for Kubernetes неполна. Нужно дополнить аннотацией в деплойменте, а также отредактировать автоматически создаваемый ConfigMap fluent-big. Чтобы разобраться, пришлось привлекать сторонний блог, расположенный на заблокированном сайте. 
https://nikolaymatrosov.medium.com/%D0%BF%D0%B8%D1%88%D0%B5%D0%BC-%D0%BB%D0%BE%D0%B3%D0%B8-%D0%B8%D0%B7-managed-k8s-%D0%B2-yandex-cloud-logging-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D0%B8-fluentbit-6ac4f4a8d391

Рекомендую дополнить следующим:

Чтобы логи с подов парсились, в деплойменте нужно указывать аннотации вида

```
  template:
    metadata:
      labels:
        app: loggen
      annotations:
        fluentbit.io/parser: app_log_parser # Имя парсера, если кастомный, нужно указывать в конфиге FluentBit
        yc.logging.tag: loggen # Тег для пометки тех подов, с которых нужно снимать логи
```

Далее, чтобы в Cloud Logging корректно передавались уровень логирование и сообщение, нужно изменить конфиг FluentBit
```
[OUTPUT]
    Name            yc-logging
    Match           yc.logging.*
    message_key     text # Имя поля для сообщения
    level_key       severity # Имя поля для уровня логирования
```
