### ISSUE TITLE
Передача логов из файла в формате JSON

### ISSUE THREAD

**Issue by financemarker** [yandex-cloud/docs#924]
С помощью агента сбора метрик я настроил запись и передачу логов из файла в Cloud Logging. 
Сообщения поступают в Cloud Logging однако только в виде простого текста, что не позволяет стороне Cloud Logging использовать запросы для фильтации.

При этом в документации  (https://yandex.cloud/ru/docs/monitoring/concepts/data-collection/unified-agent/outputs) сказано, что если сообщение - это валидный JSON, оно должно автоматически парситься. 

Подскажите - работает ли этот функционал и если да, как должна выглядеть строка в логе?
Я пробовал множество разных форматов - ничего не подошло, каждый раз все сообщение попадает в Cloud Logging как обычный текст. 

Пример моей конфигурации:

```
   ...
   output:
       plugin: yc_logs
        config:
          log_group_id: "***"
          iam:
            cloud_meta: {}
          parse_json:
            payload:
              keys: ["message"]
            timestamp:
              keys: ["timestamp"]
```

И пример того, как выглядели сообщения в логе (пробовал разные варианты - ни один не сработал):
`{"full_path": "***", "message": "'NoneType' object is not subscriptable", "method": "GET", "remote_addr": "127.0.0.1", "scheme": "http", "timestamp": "2025-03-27 18:16:37"}`

`{"json-payload": {"full_path": "***", "method": "GET", "remote_addr": "127.0.0.1", "scheme": "http"}, "message": "'NoneType' object is not subscriptable"}`

`{"payload": {"full_path": "***", "message": "'NoneType' object is not subscriptable", "method": "GET", "remote_addr": "127.0.0.1", "scheme": "http", "timestamp": "2025-03-28 10:58:55"}}`
